# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kduiAgtkJ3v15woFYp3pLUENGWexW0nj
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# =========================
# LOAD DATA
# =========================
@st.cache_data
def load_data():
    url = "https://drive.google.com/uc?id=1SUOZm4TUmvkxczY9fbCpntzPR1RIdnu0"
    df = pd.read_csv(url)
    df['month'] = df['month'].astype(str)
    df['month'] = pd.to_datetime(df['month'])
    return df

all_df = load_data()

st.title("📊 E-Commerce Data Analysis Dashboard")

# =========================
# SIDEBAR FILTER
# =========================
st.sidebar.header("Filter Data")

# Filter tanggal
min_date = all_df['month'].min()
max_date = all_df['month'].max()

start_date, end_date = st.sidebar.date_input(
    label="Pilih Rentang Waktu",
    min_value=min_date,
    max_value=max_date,
    value=[min_date, max_date]
)

# Filter kota
city_list = all_df['customer_city'].dropna().unique()
selected_city = st.sidebar.multiselect(
    "Pilih Kota",
    options=city_list,
    default=city_list
)

# APPLY FILTER
filtered_df = all_df[
    (all_df['month'] >= pd.to_datetime(start_date)) &
    (all_df['month'] <= pd.to_datetime(end_date)) &
    (all_df['customer_city'].isin(selected_city))
]

# =========================
# 1. TREN TRANSAKSI BULANAN
# =========================
st.header("1. Tren Transaksi Bulanan")

all_df['month'] = all_df['month'].astype(str)
all_df['month'] = pd.to_datetime(all_df['month'])

monthly_orders_df = all_df.set_index('month').resample('M').agg({
    "order_id": "nunique",
    "price": "sum"
})

plt.figure(figsize=(10, 5))
plt.plot(
    monthly_orders_df["order_id"],
    marker='o',
    linewidth=2,
    color="#72BCD4"
)
plt.title("Number of Orders", loc="center", fontsize=20)
plt.xticks(fontsize=10)
plt.yticks(fontsize=10)
plt.show()

monthly_orders_df = filtered_df.set_index('month').resample('M').agg({
    "order_id": "nunique",
    "price": "sum"
})

st.line_chart(monthly_orders_df["order_id"])

# =========================
# 2. REVENUE PER CITY
# =========================
st.header("2. Revenue Berdasarkan Kota")

city_revenue_df = all_df.groupby('customer_city').agg({
    "price": "sum"
}).sort_values(by="price", ascending=False)

top_city_revenue = city_revenue_df.head(10)

top_city_revenue.head(10)

plt.figure(figsize=(12, 6))
plt.bar(
    top_city_revenue.index,
    top_city_revenue["price"]
)

plt.title("Top 10 City by Revenue", fontsize=20)
plt.xlabel("City", fontsize=12)
plt.ylabel("Total Revenue", fontsize=12)
plt.xticks(rotation=45)
plt.show()

city_revenue_df = filtered_df.groupby('customer_city').agg({
    "price": "sum"
}).sort_values(by="price", ascending=False)

st.bar_chart(city_revenue_df.head(10))

# =========================
# 3. BEST & WORST PRODUCT
# =========================
st.header("3. Produk Terbaik & Terburuk")

sum_order_items_df = all_df.groupby("product_category_name")["order_item_id"] \
    .count() \
    .sort_values(ascending=False) \
    .reset_index()

sum_order_items_df.head(10)

fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(24, 6))

colors = ["#72BCD4", "#D3D3D3", "#D3D3D3", "#D3D3D3", "#D3D3D3"]

sns.barplot(x="order_item_id", y="product_category_name", data=sum_order_items_df.head(5), palette=colors, ax=ax[0])
ax[0].set_ylabel(None)
ax[0].set_xlabel(None)
ax[0].set_title("Best Performing Product", loc="center", fontsize=18)
ax[0].tick_params(axis ='y', labelsize=15)

sns.barplot(x="order_item_id", y="product_category_name", data=sum_order_items_df.sort_values(by="order_item_id", ascending=True).head(5), palette=colors, ax=ax[1])
ax[1].set_ylabel(None)
ax[1].set_xlabel(None)
ax[1].invert_xaxis()
ax[1].yaxis.set_label_position("right")
ax[1].yaxis.tick_right()
ax[1].set_title("Worst Performing Product", loc="center", fontsize=18)
ax[1].tick_params(axis='y', labelsize=15)

plt.suptitle("Best and Worst Performing Product", fontsize=20)
plt.show()

sum_order_items_df = filtered_df.groupby("product_category_name")["order_item_id"] \
    .count() \
    .sort_values(ascending=False) \
    .reset_index()

st.bar_chart(sum_order_items_df.head(10).set_index("product_category_name"))

# =========================
# 4. CUSTOMER SEGMENTATION (RFM)
# =========================

rfm_df = all_df.groupby(by="customer_id", as_index=False).agg({
    "month": "max", #mengambil tanggal order terakhir
    "order_id": "nunique",
    "price": "sum"
})
rfm_df.columns = ["customer_id", "max_order_timestamp", "frequency", "monetary"]

rfm_df["max_order_timestamp"] = pd.to_datetime(rfm_df["max_order_timestamp"])
recent_date = pd.to_datetime(all_df["month"]).max()
rfm_df["recency"] = (recent_date - rfm_df["max_order_timestamp"]).dt.days

rfm_df.drop("max_order_timestamp", axis=1, inplace=True)

rfm_df.describe()

rfm_df['r_rank'] = rfm_df['recency'].rank(ascending=False)
rfm_df['f_rank'] = rfm_df['frequency'].rank(ascending=True)
rfm_df['m_rank'] = rfm_df['monetary'].rank(ascending=True)

# normalizing the rank of the customers
rfm_df['r_rank_norm'] = (rfm_df['r_rank']/rfm_df['r_rank'].max())*100
rfm_df['f_rank_norm'] = (rfm_df['f_rank']/rfm_df['f_rank'].max())*100
rfm_df['m_rank_norm'] = (rfm_df['m_rank']/rfm_df['m_rank'].max())*100

rfm_df.drop(columns=['r_rank', 'f_rank', 'm_rank'], inplace=True)

rfm_df.head()

rfm_df['RFM_score'] = 0.15*rfm_df['r_rank_norm']+0.28 * \
    rfm_df['f_rank_norm']+0.57*rfm_df['m_rank_norm']
rfm_df['RFM_score'] *= 0.05
rfm_df = rfm_df.round(2)

rfm_df["customer_segment"] = np.where(
    rfm_df['RFM_score'] > 4.5, "Top customers", (np.where(
        rfm_df['RFM_score'] > 4, "High value customer",(np.where(
            rfm_df['RFM_score'] > 3, "Medium value customer", np.where(
                rfm_df['RFM_score'] > 1.6, 'Low value customers', 'lost customers'))))))

customer_segment_df = rfm_df.groupby(by="customer_segment", as_index=False).customer_id.nunique()
customer_segment_df

customer_segment_df['customer_segment'] = pd.Categorical(customer_segment_df['customer_segment'], [
    "lost customers", "Low value customers", "Medium value customer",
    "High value customer", "Top customers"
])

plt.figure(figsize=(10, 5))
colors_ = ["#72BCD4", "#72BCD4", "#D3D3D3", "#D3D3D3", "#D3D3D3"]

sns.barplot(
    x="customer_id",
    y="customer_segment",
    data=customer_segment_df.sort_values(by="customer_segment", ascending=False),
    palette=colors_
)
plt.title("Number of Customer for Each Segment", loc="center", fontsize=15)
plt.ylabel(None)
plt.xlabel(None)
plt.tick_params(axis='y', labelsize=12)
plt.show()

rfm_df = filtered_df.groupby(by="customer_id", as_index=False).agg({
    "month": "max",
    "order_id": "nunique",
    "price": "sum"
})

rfm_df.columns = ["customer_id", "max_order_timestamp", "frequency", "monetary"]

rfm_df["max_order_timestamp"] = pd.to_datetime(rfm_df["max_order_timestamp"])
recent_date = pd.to_datetime(filtered_df["month"]).max()

rfm_df["recency"] = (recent_date - rfm_df["max_order_timestamp"]).dt.days

st.write("### Data Preview")
st.dataframe(filtered_df.head())

# =========================
# FOOTER
# =========================
st.write("Dashboard dibuat untuk analisis data e-commerce 🚀")