# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kduiAgtkJ3v15woFYp3pLUENGWexW0nj
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# =========================
# LOAD DATA
# =========================
@st.cache_data
def load_data():
    url = "https://drive.google.com/uc?id=1SUOZm4TUmvkxczY9fbCpntzPR1RIdnu0"
    df = pd.read_csv(url)
    df['month'] = df['month'].astype(str)
    df['month'] = pd.to_datetime(df['month'])
    return df

all_df = load_data()

st.title("📊 E-Commerce Data Analysis Dashboard")

# =========================
# 1. TREN TRANSAKSI BULANAN
# =========================
st.header("1. Tren Transaksi Bulanan")

monthly_orders_df = all_df.set_index('month').resample('M').agg({
    "order_id": "nunique",
    "price": "sum"
})

fig, ax = plt.subplots(figsize=(10,5))
ax.plot(
    monthly_orders_df["order_id"],
    marker='o',
    linewidth=2,
    color="#72BCD4"
)
ax.set_title("Number of Orders", fontsize=15)
st.pyplot(fig)

# =========================
# 2. REVENUE PER CITY
# =========================
st.header("2. Revenue Berdasarkan Kota")

city_revenue_df = all_df.groupby('customer_city').agg({
    "price": "sum"
}).sort_values(by="price", ascending=False).head(10)

fig, ax = plt.subplots(figsize=(10,5))
ax.bar(city_revenue_df.index, city_revenue_df["price"])
ax.set_title("Top 10 City by Revenue")
ax.set_xticklabels(city_revenue_df.index, rotation=45)
st.pyplot(fig)

# =========================
# 3. BEST & WORST PRODUCT
# =========================
st.header("3. Produk Terbaik & Terburuk")

product_df = all_df.groupby('product_category_name').agg({
    "price": "sum"
}).sort_values(by="price", ascending=False)

top_products = product_df.head(10)
worst_products = product_df.tail(10)

# TOP PRODUCTS
st.subheader("Top 10 Best Products")
fig, ax = plt.subplots(figsize=(10,5))
ax.bar(top_products.index, top_products["price"])
ax.set_xticklabels(top_products.index, rotation=45)
st.pyplot(fig)

# WORST PRODUCTS
st.subheader("Top 10 Worst Products")
fig, ax = plt.subplots(figsize=(10,5))
ax.bar(worst_products.index, worst_products["price"])
ax.set_xticklabels(worst_products.index, rotation=45)
st.pyplot(fig)

# =========================
# 4. CUSTOMER SEGMENTATION (RFM)
# =========================

st.header("4. Customer Segmentation (RFM)")

# =========================
# PASTIKAN FORMAT DATETIME
# =========================
all_df["order_purchase_timestamp"] = pd.to_datetime(all_df["order_purchase_timestamp"])

# =========================
# HITUNG RFM
# =========================
rfm_df = all_df.groupby("customer_id").agg({
    "order_purchase_timestamp": "max",   # Recency
    "order_id": "nunique",               # Frequency
    "price": "sum"                       # Monetary
}).reset_index()

rfm_df.columns = ["customer_id", "last_order", "frequency", "monetary"]

# =========================
# HITUNG RECENCY
# =========================
recent_date = all_df["order_purchase_timestamp"].max()
rfm_df["last_order"] = pd.to_datetime(rfm_df["last_order"])

rfm_df["recency"] = (recent_date - rfm_df["last_order"]).dt.days

# =========================
# SCORING RFM (ANTI ERROR)
# =========================
rfm_df["R"] = pd.qcut(rfm_df["recency"], 5, labels=[5,4,3,2,1])
rfm_df["F"] = pd.qcut(rfm_df["frequency"].rank(method="first"), 5, labels=[1,2,3,4,5])
rfm_df["M"] = pd.qcut(rfm_df["monetary"], 5, labels=[1,2,3,4,5])

# ubah ke integer
rfm_df["R"] = rfm_df["R"].astype(int)
rfm_df["F"] = rfm_df["F"].astype(int)
rfm_df["M"] = rfm_df["M"].astype(int)

# =========================
# HITUNG RFM SCORE
# =========================
rfm_df["RFM_SCORE"] = rfm_df["R"] + rfm_df["F"] + rfm_df["M"]

# =========================
# SEGMENTASI
# =========================
def segment(score):
    if score >= 13:
        return "Top"
    elif score >= 10:
        return "High"
    elif score >= 7:
        return "Medium"
    elif score >= 4:
        return "Low"
    else:
        return "Lost"

rfm_df["segment"] = rfm_df["RFM_SCORE"].apply(segment)

# =========================
# VISUALISASI
# =========================
segment_count = rfm_df["segment"].value_counts()

fig, ax = plt.subplots(figsize=(8,5))
ax.bar(segment_count.index, segment_count.values)
ax.set_title("Customer Segmentation (RFM)")
ax.set_xlabel("Segment")
ax.set_ylabel("Number of Customers")

st.pyplot(fig)

# =========================
# TAMPILKAN DATA (OPSIONAL)
# =========================
st.subheader("Sample RFM Data")
st.dataframe(rfm_df.head())

# =========================
# FOOTER
# =========================
st.write("Dashboard dibuat untuk analisis data e-commerce 🚀")