# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kduiAgtkJ3v15woFYp3pLUENGWexW0nj
"""

import streamlit as st
import pandas as pd
import numpy as np

# =========================
# LOAD DATA
# =========================
@st.cache_data
def load_data():
    url = "https://drive.google.com/uc?id=1SUOZm4TUmvkxczY9fbCpntzPR1RIdnu0"
    df = pd.read_csv(url)
    df['month'] = pd.to_datetime(df['month'])
    return df

all_df = load_data()

st.title("📊 E-Commerce Data Analysis Dashboard")

# =========================
# FILTER
# =========================
st.subheader("🔎 Filter Data")

col1, col2 = st.columns(2)

with col1:
    min_date = all_df['month'].min()
    max_date = all_df['month'].max()

    date_range = st.date_input(
        "Pilih Rentang Waktu",
        value=[min_date, max_date],
        min_value=min_date,
        max_value=max_date
    )

if len(date_range) == 2:
    start_date, end_date = date_range
else:
    start_date = end_date = date_range[0]

start_date = pd.to_datetime(start_date)
end_date = pd.to_datetime(end_date)

with col2:
    city_list = sorted(all_df['customer_city'].dropna().unique())
    selected_city = st.multiselect(
        "Pilih Kota",
        options=city_list,
        default=city_list
    )

filtered_df = all_df[
    (all_df['month'] >= start_date) &
    (all_df['month'] <= end_date) &
    (all_df['customer_city'].isin(selected_city))
]

st.write(f"Jumlah data: {filtered_df.shape[0]}")

# =========================
# 1. TREN TRANSAKSI
# =========================
st.header("1. Tren Transaksi Bulanan")

monthly_orders_df = filtered_df.set_index('month').resample('M').agg({
    "order_id": "nunique"
})

st.line_chart(monthly_orders_df)

st.caption("Menunjukkan tren jumlah transaksi setiap bulan.")

# =========================
# 2. REVENUE PER CITY
# =========================
st.header("2. Revenue Berdasarkan Kota")

city_revenue_df = filtered_df.groupby("customer_city")["price"].sum().sort_values(ascending=False)

st.bar_chart(city_revenue_df.head(10))

# tabel tambahan (opsional tapi bagus)
st.subheader("📋 Top 10 Kota")
st.dataframe(city_revenue_df.head(10).reset_index())

st.caption("Top kota dengan kontribusi revenue terbesar.")

# =========================
# 3. BEST & WORST PRODUCT
# =========================
st.header("3. Produk Terbaik & Terburuk")

sum_order_items_df = filtered_df.groupby("product_category_name")["order_item_id"] \
    .count() \
    .sort_values(ascending=False) \
    .reset_index()

sum_order_items_df.columns = ["product_category_name", "total_sold"]

col1, col2 = st.columns(2)

with col1:
    st.subheader("🏆 Best Performing Product")
    st.bar_chart(
        sum_order_items_df.head(5).set_index("product_category_name")
    )

with col2:
    st.subheader("⚠️ Worst Performing Product")
    st.bar_chart(
        sum_order_items_df.sort_values(by="total_sold", ascending=True)
        .head(5)
        .set_index("product_category_name")
    )

# tabel (WAJIB)
st.subheader("📋 Detail Produk")

col3, col4 = st.columns(2)

with col3:
    st.write("Top 5 Produk Terlaris")
    st.dataframe(sum_order_items_df.head(5))

with col4:
    st.write("Bottom 5 Produk Terburuk")
    st.dataframe(
        sum_order_items_df.sort_values(by="total_sold", ascending=True).head(5)
    )

st.caption("Produk terbaik dan terburuk berdasarkan jumlah item terjual.")

# =========================
# 4. RFM ANALYSIS
# =========================
st.header("4. Customer Segmentation (RFM)")

rfm_df = filtered_df.groupby(by="customer_id", as_index=False).agg({
    "month": "max",
    "order_id": "nunique",
    "price": "sum"
})

rfm_df.columns = ["customer_id", "max_order_timestamp", "frequency", "monetary"]

rfm_df["max_order_timestamp"] = pd.to_datetime(rfm_df["max_order_timestamp"])
recent_date = filtered_df["month"].max()
rfm_df["recency"] = (recent_date - rfm_df["max_order_timestamp"]).dt.days

rfm_df.drop("max_order_timestamp", axis=1, inplace=True)

# ranking
rfm_df['r_rank'] = rfm_df['recency'].rank(ascending=False)
rfm_df['f_rank'] = rfm_df['frequency'].rank(ascending=True)
rfm_df['m_rank'] = rfm_df['monetary'].rank(ascending=True)

# normalisasi
rfm_df['r_rank_norm'] = (rfm_df['r_rank']/rfm_df['r_rank'].max())*100
rfm_df['f_rank_norm'] = (rfm_df['f_rank']/rfm_df['f_rank'].max())*100
rfm_df['m_rank_norm'] = (rfm_df['m_rank']/rfm_df['m_rank'].max())*100

rfm_df.drop(columns=['r_rank', 'f_rank', 'm_rank'], inplace=True)

# scoring
rfm_df['RFM_score'] = (
    0.15 * rfm_df['r_rank_norm'] +
    0.28 * rfm_df['f_rank_norm'] +
    0.57 * rfm_df['m_rank_norm']
)

rfm_df['RFM_score'] *= 0.05
rfm_df = rfm_df.round(2)

# segment
rfm_df["customer_segment"] = np.where(
    rfm_df['RFM_score'] > 4.5, "Top customers", np.where(
        rfm_df['RFM_score'] > 4, "High value customer", np.where(
            rfm_df['RFM_score'] > 3, "Medium value customer", np.where(
                rfm_df['RFM_score'] > 1.6, "Low value customers", "Lost customers"
            )
        )
    )
)

segment_df = rfm_df.groupby("customer_segment")["customer_id"].nunique()

segment_order = [
    "Lost customers",
    "Low value customers",
    "Medium value customer",
    "High value customer",
    "Top customers"
]

segment_df = segment_df.reindex(segment_order)

st.bar_chart(segment_df)

# tabel segment
st.subheader("📋 Jumlah Customer per Segment")
st.dataframe(segment_df.reset_index().rename(columns={
    "index": "segment",
    "customer_id": "total_customer"
}))

# tabel detail (IMPORTANT)
st.subheader("📋 Sample Customer (Top RFM Score)")
st.dataframe(
    rfm_df.sort_values(by="RFM_score", ascending=False).head(10)
)

st.caption("Segmentasi pelanggan berdasarkan metode RFM dari notebook.")

# =========================
# FOOTER
# =========================
st.markdown("---")
st.write("Dashboard interaktif berdasarkan hasil analisis data e-commerce 🚀")