# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kduiAgtkJ3v15woFYp3pLUENGWexW0nj
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# =========================
# LOAD DATA
# =========================
@st.cache_data
def load_data():
    url = "https://drive.google.com/uc?id=1SUOZm4TUmvkxczY9fbCpntzPR1RIdnu0"
    df = pd.read_csv(url)
    df['month'] = pd.to_datetime(df['month'])
    return df

all_df = load_data()

st.title("📊 E-Commerce Data Analysis Dashboard")

# =========================
# FILTER (DI ATAS)
# =========================
st.subheader("🔎 Filter Data")

col1, col2 = st.columns(2)

with col1:
    min_date = all_df['month'].min()
    max_date = all_df['month'].max()

    date_range = st.date_input(
        "Pilih Rentang Waktu",
        value=[min_date, max_date],
        min_value=min_date,
        max_value=max_date
    )

# handle error date_input
if len(date_range) == 2:
    start_date, end_date = date_range
else:
    start_date = end_date = date_range[0]

start_date = pd.to_datetime(start_date)
end_date = pd.to_datetime(end_date)

with col2:
    city_list = all_df['customer_city'].dropna().unique()
    selected_city = st.multiselect(
        "Pilih Kota",
        options=city_list,
        default=city_list
    )

# APPLY FILTER
filtered_df = all_df[
    (all_df['month'] >= start_date) &
    (all_df['month'] <= end_date) &
    (all_df['customer_city'].isin(selected_city))
]

st.write("Jumlah data:", filtered_df.shape[0])

# =========================
# 1. TREN TRANSAKSI BULANAN
# =========================
st.header("1. Tren Transaksi Bulanan")

monthly_orders_df = filtered_df.set_index('month').resample('M').agg({
    "order_id": "nunique",
    "price": "sum"
})

st.line_chart(monthly_orders_df["order_id"])

# =========================
# 2. REVENUE PER CITY
# =========================
st.header("2. Revenue Berdasarkan Kota")

city_revenue_df = filtered_df.groupby('customer_city')['price'].sum().sort_values(ascending=False)

st.bar_chart(city_revenue_df.head(10))

# =========================
# 3. BEST PRODUCT
# =========================
st.header("3. Produk Terlaris")

product_df = filtered_df.groupby("product_category_name")["order_item_id"] \
    .count() \
    .sort_values(ascending=False)

st.bar_chart(product_df.head(10))

# =========================
# 4. RFM ANALYSIS
# =========================
st.header("4. Customer Segmentation (RFM)")

rfm_df = filtered_df.groupby(by="customer_id", as_index=False).agg({
    "month": "max",
    "order_id": "nunique",
    "price": "sum"
})

rfm_df.columns = ["customer_id", "max_order_timestamp", "frequency", "monetary"]

recent_date = filtered_df["month"].max()
rfm_df["recency"] = (recent_date - rfm_df["max_order_timestamp"]).dt.days

# segmentasi sederhana
rfm_df["segment"] = pd.qcut(rfm_df["monetary"], 4, labels=[
    "Low", "Medium", "High", "Top"
])

segment_df = rfm_df["segment"].value_counts()

st.bar_chart(segment_df)

# =========================
# FOOTER
# =========================
st.caption("Dashboard dibuat untuk analisis data e-commerce 🚀")